# Compiler and flags
CXX := g++
CXXFLAGS := -std=c++11 -Wall -Wextra -g
LDFLAGS := -Llib/sdl_lib -lSDL2 -lSDL2main -lSDL2_image

# Include directories
INCLUDES := -Iinclude -Iinclude/sdl -Iinclude/imgui -Iinclude/stb -Iinclude/nlohmann -Iinclude/myheaders

# Source and object files
SRCS := src/Main.cpp src/Player.cpp src/Map.cpp src/Room.cpp src/SaveManager.cpp \
        lib/stb/stb_image.c \
        include/imgui/imgui.cpp include/imgui/imgui_draw.cpp \
        include/imgui/imgui_widgets.cpp include/imgui/imgui_tables.cpp \
        include/imgui/imgui_impl_sdl2.cpp include/imgui/imgui_impl_sdlrenderer2.cpp
OBJS := $(SRCS:.cpp=.o)
OBJS := $(OBJS:.c=.o)

# Target executable
TARGET := mosze.exe

# Default target
all: $(TARGET)

# Link step
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^ $(LDFLAGS)

# Compile step for .cpp and .c files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

%.o: %.c
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

# Clean up
clean:
	rm -f $(OBJS) $(TARGET)
